ocrmypdf/main.py

OCRmyPDF exits when a PDF file is a little bit broken but is successfully repaired by qpdf.  I think it should just display the warning and continue.
Here's a sample error display:
WARNING: /home/shemgp/Desktop/Rusli Heince - Clearance.pdf: reported number of objects (7) inconsistent with actual number of objects (8)
WARNING: /home/shemgp/Desktop/Rusli Heince - Clearance.pdf: file is damaged
WARNING: /home/shemgp/Desktop/Rusli Heince - Clearance.pdf (object 5 0, file position 446097): expected 5 0 obj
WARNING: /home/shemgp/Desktop/Rusli Heince - Clearance.pdf: Attempting to reconstruct cross-reference table
WARNING: /home/shemgp/Desktop/Rusli Heince - Clearance.pdf (object 2 0, file position 445846): stream keyword followed by carriage return only
WARNING: /home/shemgp/Desktop/Rusli …

Don't exit when qpdf repairs the file successfully but displays warning

---

README.rst

Update also the 2nd article link to use a permalink, too.
Signed-off-by: Stefan Weil <sw@weilnetz.de>

Replace broken link to c't article by permalink

---

README.rst

Just making explicit the way to get help on command syntax after I searched for and found it in #18.

Adding explicit reference to help

---

tests/test_main.py

Skip the test if the fair use restricted milk.pdf is not present.
When #93 is resolved this could be generalised for all tests using restricted files that can be opted-out from.

pytest skipif for milk.pdf test

---

README.rst

`brew install tesseract` just installed the english language pack not French, German or Spanish

Update "Installing on Mac OS X"

---

docs/conf.py

Mathjax isn't actually needed for OCRmyPDF's docs, but enabling this
extension causes the browser to download a copy of mathjax.js from
cdn.mathjax.org anyway.
I have to disable this for the offline docs bundled with Debian, but
since you're not using mathjax, it would be nice to have the diff merged
upstream.
Thanks.

disable mathjax sphinx extension

---

ocrmypdf/__main__.py

The 4th argument of `re.sub()` is maximum number of substitutions, not flags.
Moreover, `re.MULTILINE` affects only semantics of `^` and `$`, so it wouldn't have any effect on this regular expression.
Found using [pydiatra](https://github.com/jwilk/pydiatra).

Remove misplaced flags from re.sub() call

---

.travis/osx_before_install.sh

Homebrew removed python3 and python now defaults to version 3. Here we
use `brew upgrade python` to upgrade the pre-installed version of
python to python3.

Fix Homebrew python package

---

setup.cfg

The '-n' command line argument is not supported by recent pytest, at least the version in Debian.  Thanks.

remove addopts key from tool:pytest section of setup.cfg

---

tests/test_main.py

They're both the same thing:
https://github.com/python-pillow/Pillow/blob/master/src/PIL/__init__.py

Use more standard __version__ rather than PILLOW_VERSION

---

docs/installation.rst

And adding a workaround to a wrong dependencies definition on https://aur.archlinux.org/packages/python-pikepdf/
ocrmypdf is not on the main arch linux repository it is on a user one, so it is not available through pacman and the user can install via yaourt to manage the aur packages. Maybe the user needs to install yaourt itself, but this is implicity.

Updating Arch Linux instalation

---

README.md
docs/installation.rst
docs/languages.rst

OCRmyPDF will be available in Fedora 29+.

Add Fedora install instructions.

---

docs/installation.rst

Thanks, as ever, for the tremendous work and continuous improvements to ocrmypdf.  These installation options are terrific and I am starting to explore the docker image webservice which is a very interesting option.
Not completely sure this PR change is correct, but I think `docker pull jbarlow83/ocrmypdf-webservice` might be the intended command for getting the webservice version.  It installs as expected where the original suggests that polyglot is the docker image name for both of the last two options in the table:
```
docker pull jbarlow83/ocrmypdf-webservice
Using default tag: latest
latest: Pulling from jbarlow83/ocrmypdf-webservice
38e2e6cd5626: Already exists 
705054bc3f5b: Already exists 
c7051e069564: Already exists 
7308e914506c: Already exists 
3977c3cd82d1: Already exists …
```

Adjust the docker pull command for webservice

---

docs/installation.rst

The default homebrew formula installs only the English language pack.
Another brew formula exists to install all other language packs.
This makes it easier than having to do the whole install manually.

Update documentation: how to install other language packs on macOS

---

misc/ocrmypdf

bash completion file for ocrmypdf
requires bash-completion installed https://github.com/scop/bash-completion
~~file must be copied to completion folder e.g. /usr/share/bash-completion/completions~~
Edit:
possible solution for this issue: #333
Just source the script after download:
`source /<yourDownloadPath>/ocrmypdf`
Now enter: `ocrmypdf --<Tab>`   
Or use this gitpod share: [![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io#snapshot/f6215430-9f60-4555-a7a2-890193ba43c3)
`source completion/ocrmypdf`
Now enter: `ocrmypdf --<Tab>`   
For installation options refer to [scop/bash-completion](https://github.com/scop/bash-completion)

Add bash completion

---

docs/batch.rst
misc/watcher.py

This pull request is a followup to #466.
This PR fixes 2 bugs in `watcher.py` and adds additional functionality.
Bug fixes:
1. `Fix double-fire on create and modify events`: the `HandleObserverEvent` fires on both `create` and `modified` events. Depending on how the file is written to disk, this may cause 2 events to be fired, OCR'ing the PDF twice. This fix listens only for the `create` event and only fires once.
2. `Fix FileInput error when reading from docker volume`: Non-deterministicly, watchdog may fire a `create` even when a file is not fully written to disk on a docker volume. We fix this by watching the file size every second and waiting for new data to stop being written to disk. This solution works 100% reliabily my testing, both docker and non-docker.
New functonality: 
1. …

Watched folder bug fixes, new flags, and docs updates.

---

docs/installation.rst

Python 3.7 is the new default version since 2020Q1 which is reflected in
the new prefix (= py37-).
Also update the current available FreeBSD versions:
* FreeBSD 11.2-RELEASE has reached its End-of-Life in 2019Q4
* FreeBSD 12.1-RELEASE was also introduced in 2019Q4

Update installation instructions for FreeBSD

---

docs/installation.rst

This describes how to use the AUR package on a minimal install, as per
the discussion in #494.
There may be formatting mistakes. I don't use RST myself, so I wrote the
instructions in Markdown, converted via Pandoc, and gave the output a
quick comparison against the rest of the installation docs.

Demonstrate installing the AUR package without a helper

---

docs/installation.rst

`pip3` defaults to the system's outdated version which downloads wrong qpdf package.

fix install instructions for Ubunti 16.04

---

docs/installation.rst

The python-pdfminer.six package is now available in the official Arch repositories. The dependency will be automatically resolved when installing the OCRmyPDF AUR package.

docs: update Arch Linux install instructions

---

src/ocrmypdf/pdfinfo/info.py

The built-in function being used does not require comprehension and can work directly with a generator expression. Using a generator expression within these functions is faster than using a comprehension.

Unnecessary comprehension

---

src/ocrmypdf/leptonica.py

Checks if `zlib` can be loaded from the same location where `liblept` was found. Usually this is the case if `liblept` was loaded from Tesseract's installation directory. If not, it falls back on `find_library()`
fixes #631

load zlib before liblept on windows

---

docs/installation.rst

Add `unpaper` as dependency for Ubuntu 18.04 for `clean` option to work

Add 'unpaper' dependency for Ubuntu 18.04

---

README.md

Note `brew` command for installing additional languages on macOS.

Add macOS brew language support

---

docs/installation.rst

There is a small typo in docs/installation.rst.
Should read `installed` rather than `instsalled`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, instsalled -> installed

---

src/ocrmypdf/_pipeline.py
src/ocrmypdf/_validation.py
tests/test_pipeline.py
tests/test_validation.py

After a few short checks it looks like --sidecar and --pages can work together and produce reasonable results.
This PR relaxes this constraint and prints skipped pages as ranges.

Allow --sidecar along --pages

---

docs/languages.rst

Just installed ocrmypdf on windows and found that there are no additional languages installed. So I changed the documentation how to add new languages on windows.

Updated documentation for windows and additional languages

---

docs/languages.rst

Hi!
On Ubuntu and Arch Linux, the three-letter code for French is not `fre` but `fra` in Tesseract.
I went ahead and also fixed this for Fedora, under the assumption that the code is identical.

Fix code of French language pack in languages.rst

---

docs/installation.rst

The Python default version was changed from 3.7 to 3.8 at the end of April.  For the new quarterly branch, 2021Q3, Python 3.8 has also been the default version since July.

Update the FreeBSD specific parts of the documentation

---

misc/watcher.py
setup.cfg

The breaking change was dropping support for macOS 10.12 and earlier, which doesn't affect us.

Allow watchdog 2.

---

misc/webservice.py
setup.cfg

There are breaking changes, but it seems like it doesn't break anything to use it.

Allow flask 2 for webservice

---

docs/conf.py

This polishes the fix for #837 and maybe makes it possible to reference ocrmypdf with intersphinx, which currently doesn't seem to work.

[ci skip] docs/conf.py: add intersphinx mapping to make external links work

---

src/ocrmypdf/_exec/ghostscript.py

Specifying option --oversample tends to introduce upsampling in rendering
by rasterizing page to an higher DPI.
This upsampling improves OCR results, but a correct choice of interpolation
method can increase even more the OCR quality.
Ghostscript seems to use a nearest interpolation as default choice for pdf.
This method doesn't average new introduced pixels with original pixels
resulting in an almost similar image but with more pixels.
Providing -dInterpolateControl=-1 force switching interpolation on.
In this commit the above option is passed to all ghostscript rendering
calls.
After testing, rendering a page at same DPI with interpolation
enabled does not introduce significant time overhead.
time (repeat 40 gs -dQUIET -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m \
-dFirstPage=1 …

ghostscript: force interpolation when rendering

---

docs/languages.rst

I spent quite some time searching until I asked [a question on the Gentoo Forums](https://forums.gentoo.org/viewtopic.php?p=8696103).
Maybe this PR makes me the last one going through that search.

Add Gentoo Language Installation Instructions

---

setup.cfg

Fixes #970. Fixes #969.
The [changes](https://github.com/pdfminer/pdfminer.six/releases/tag/20220524) in 20220524 are minimal.

Allow pdfminer.six 20220524

---

src/ocrmypdf/__main__.py

Some sandboxing solutions don't allow calling `os.nice()`.

ignore PermissionError when calling os.nice()

---

docs/batch.rst
misc/watcher.py

This adds a feature from existing OCRmyPDF watchdog Docker containers like [@meyayl/ocrmypdf-batch](https://github.com/meyayl/ocrmypdf-batch) and [@unze/ocrmypdf-watchdog](https://github.com/unze/ocrmypdf-watchdog). With this option, the input directory can be kept clean from already processed files, without losing the originals.

watcher: Add an option to archive processed originals

---

docs/cookbook.rst

Add missing dash in warning about `--clean-final` and `--remove-background` commands.

Fix typo in cookbook.rst

---

README.md

ocrmypdf installation via nix now works on M1 Mac (aarch64-darwin)

Update README to show nix package manager install option

---

snapcraft.yaml

This patch includes a jbig2enc build into the snap package, allow the
user to run OcrMyPDF with the --jbig2-lossy option.
Signed-off-by: 林博仁(Buo-ren Lin) <Buo.Ren.Lin@gmail.com>

snap: add --jbig2-lossy support

---

docs/jbig2.rst

Packages needed to install jbig2 encoding are mentioned for Ubuntu systems but are missing for other systems. This commit adds the infomation in the documentation what the packages are called on Fedora systems: libtool and leptonica-devel.
I tried it out and it works. No further investigation happened to rule out that some package installed on my system might be necessary as well.

add Fedora packages in jbig2 installation documentation

---

docs/installation.rst

Link to [`formulae.brew.sh`](https://formulae.brew.sh/formula/ocrmypdf) as seen in [other repositories](https://github.com/search?type=code&q=/shields.io\/homebrew/+language:reStructuredText) instead of ~[`brewformulas.org`](http://brewformulas.org/Ocrmypdf)~ ([offline since 2020](https://gitlab.com/zedtux/brewformulas.org/issues/223#note_322019672)), to fix #1057.

substitute broken link (#1057)

---

snapcraft.yaml

Currently the snap package no longer contains the main Python package of OCRmyPDF due to the fact that [Snapcraft doesn't run the `pip install .` command when the setup.py isn't detected in the source tree][1].  This patch incorporates a workaround from [Chris Patterson at the Snapcraft Forum][2] to generate a setup.py file from the pyproject.toml to make the package works again.
[1]: [Line 143 of snapcraft/python.py at 0e2cf91 · snapcore/snapcraft · GitHub](https://github.com/snapcore/snapcraft/blob/0e2cf91/snapcraft_legacy/plugins/v2/python.py#L143)
[2]: [Ian Johnson's reply in "Building a core20 python snap using pyproject.toml - snapcraft - snapcraft.io"](https://forum.snapcraft.io/t/building-a-core20-python-snap-using-pyproject-toml/22028/2)
Fixes #1082.

Fix snap package building (#1082)

---

src/ocrmypdf/_pipeline.py
tests/resources/meta.pdf
tests/test_metadata.py

Passing --title='', --subject='', author='', or keywords='' is currently ignored. As a workaround, users tend to pass a space when they do not want such original metadata to carry forward. It is more desirable to be able to simply unset the output metadata rather than setting it to " ". This includes a test to confirm this change continues to work correctly as previously requested along with the associated test resource pdf. Please let me know if anything further is desired. Thanks!

Allow title, subject, author, and keywords to be unset with an empty string argument

---

.github/workflows/build.yml

This PR adds a quick job to create a GitHub release and upload the build wheel and sdist to it.  I opted for a new job rather than adding on tothe pypi upload.  The release doesn't have any content or title, since the release notes are not something that are easily parseable.
An example release looks like this: https://github.com/stumpylog/OCRmyPDF/releases  Github seems to fill in some description, it's not actually set by the action used here.  I think it's either the last commit or tag message.
Fixes #1085

Enables creation of a release and uploading the build assets to it

---

README.md
docs/installation.rst

As discussed in / closes #1129.
I chose commands most Gentoo users would probably use (there are multiple ways on Gentoo) and also opted not to increase the width of the other table rows to maintain readability of the markdown sources.
I also corrected the table entry for `macOS (nix)` while at it (removed superfluous space character).
Let me know what you think.

Add installation instructions for Gentoo Linux to README.md

---

docs/batch.rst

Updated the documentation to reflect the archive directory `watcher.py` expects by default.

Correct the archive dir name in `Watched folders with Docker`

---

docs/performance.rst

The current performance advice does not match the documentation of the flag:
> --fast-web-view MEGABYTES
> If the size of file is more than this threshold (in MB), then linearize the PDF for fast web viewing. This allows the PDF to be displayed before it is fully downloaded in web browsers, but increases the space required slightly. By default we skip this for small files which do not benefit. **If the threshold is 0 it will be apply to all files. Set the threshold very high to disable.**

Fix performance advice to match --fast-web-view documentation

---

docs/jbig2.rst

These tools are required for a successful install of JBIG2 on Ubuntu. Otherwise, the install will fail with
`Something went wrong, bailing out!`

Add autotools automake libtool and leptonica requirements

---

docs/installation.rst
src/ocrmypdf/pdfa.py

I recently came across some broken links included in the documentation for this project. This pull request includes:
- Fix links for Fedora, Arch, and HEAD revision installation
- Update info for Fedora installation (Fedora 39 has been out since November 2023)
- Fix references to the JBIG2 installation page (Some links are currently throwing 404 errors)
- Update a link to some Adobe documentation

Fix Broken Documentation Links

---

README.md
docs/installation.rst

I recently contributed (and will maintain) the `ocrmypdf` [port](https://ports.macports.org/port/ocrmypdf/details/) in the MacPorts project. This PR simply adds the install information to the README and docs.

added Macports install information

---

pyproject.toml

In 0.12.1, Typer was significantly reorganized.
- `typer-slim` is the library (for `import typer`)
- `typer-slim[standard]` adds optional dependencies (currently `rich` and `shellingham`, basically equivalent to the old `typer[all]`)
- `typer-cli` is the `typer` command-line tool
- `typer` is now basically a metapackage that brings in *all of the above*, and it no longer has an `all` extra
Pip will warn about this and proceed,
```
WARNING: typer 0.12.1 does not provide the extra 'all'
```
but there are other tools that will fail hard when asked to resolve a (now) nonexistent extra.
Since this project doesn’t need the `typer` command-line tool, it looks like changing the dependency to `typer-slim[standard]` is the best way forward.
See https://typer.tiangolo.com/release-notes/#0121 and …

Update the typer[all] dependency to typer-slim[standard]

---

docs/installation.rst

the '--needed' flag only installs the package if it isn't installed, otherwise it would reinstall it if already installed.

Add '--needed' flag to arch base-devel install command

---

docs/installation.rst

python3 returns "/usr/bin/python: Relative module names not supported"

Update installation.rst "python -m venv .venv"

---

tests/test_rotation.py

Before 42ff7fc84289a885c86d4629ebcf8dd9a65cef2d, `make_rotate_test` always used `resources / 'typewriter.png'`, but after the change the second call accidentally used just `resources`, which is a directory, and fails to open.

Fix broken test_rotate_page_level

---

docs/advanced.rst

Tested on   OCRmyPDF packaged for snap
snap-id: 4gaxtpdrLWomuJZubaPeur6sfzfkG1Do
channels:   latest/stable:    v16.4.2+git1.39010dd2 2024-07-30 (171)
The infix for two temp files is ocr_hocr, not ocr_tess.
Files are stored in, e.g. /tmp/snap-private-tmp/snap.ocrmypdf/tmp/ocrmypdf.io.pyzqxrb7
(still, the program says it is in /tmp)

Doc: new infix for temp files; snap temp files folder

---

docs/conf.py

This will break somewhere in Sphinx 8.

Update intersphinx mapping to current format

---

src/ocrmypdf/hocrtransform/_hocr.py

If the HOCR contains overlapping words in the same line or the words are not ordered in reading-direction, `space_box.width` might be negative. This leads to more issues with the calculation of font width etc, producing text boxes that are way larger than the actual bbox set within the hocr-file

hocr: only add space if boxwidth is positive

---

src/ocrmypdf/_graft.py
tests/test_graft.py

strip_invisible_text resets the text render mode on each `BT` (begin text) command. However the text state is not actually reset for each text element, only for each page.
The pdf reference says:
> The text state operators can appear outside text objects, and the values they set
> are retained across text objects in a single content stream. Like other graphics
> state parameters, these parameters are initialized to their default values at the
> beginning of each page.
>
> -- https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/pdfreference1.7old.pdf#page=397
With the current implementation, a text object is only deleted if it contains a `3 Tr` command (setting the text rendering mode to invalid). However the rendering mode may be set once and then not changed for multiple text …

graft: fix invisible text appearing after strip_invisible_text

---

src/ocrmypdf/_progressbar.py

This pull request refines the documentation for the `ProgressBar(Protocol)` in `_progressbar.py`:
1. **Clarifies usage of `n` vs. `completed`:**  
- Emphasizes that `n` is generally used for page-based increments.  
- Explains that `completed` is especially useful for percentage-based tracking.
2. **Adds a Short Example:**  
- Demonstrates a simple implementation showcasing both incremental and absolute completion updates for a plugin
3. **Expands the Docstrings:**  
- More information about the args used in `__init__`
- **Better Guidance**: A clearer protocol for developers who need to customize or create their own progress bars.  
- **Forward Compatibility**: Stresses ignoring unrecognized `**kwargs` so it won’t break on future OCRmyPDF releases.  
- **Improved Examples**: The code …

Improve ProgressBar docstring to clarify usage of increments and completion

---

src/ocrmypdf/hocrtransform/_hocr.py

Previously in the hOCR transform, [`ocr_caption`](https://kba.github.io/hocr-spec/1.2/#sec-ocr_caption) spans were ignored. This PR fixes that issue so that OCRmyPDF processes image caption lines instead of ignoring them. As far as I know, `ocr_caption` is the only missing line type that Tesseract can produce, see: https://github.com/tesseract-ocr/tesseract/blob/3157ff0e741ea5c85e16fbd1c6edf20f30eccbd3/src/api/hocrrenderer.cpp#L231-L248

Process ocr_caption lines

---

docs/installation.rst

See rendering on https://github.com/alexpdp7/OCRmyPDF/blob/main/docs/installation.rst#installing-on-windows

Correct the installation instructions for Windows

---

src/ocrmypdf/pdfinfo/layout.py

A followup fix to #1378.
The progress bar stalls at 0% until all pages are parsed and cached, which takes pretty much of the total run time (thanks to #1380). Fix this by lazy caching.
Test file: [blank-10k.pdf](https://github.com/user-attachments/files/16637412/blank-10k.pdf)
Test command: `ocrmypdf --redo-ocr blank-10k.pdf out.pdf`

Fix "Scanning contents" progress bar with --redo-ocr

---

docs/docker.rst

I've fiddled/struggled with this by myself, by getting a permission error like this one:
```shell
OutputFileAccessError: Output file location (./output.pdf) is not a writable file.
``` 
I've loosely followed and found https://github.com/containers/podlet?tab=readme-ov-file#in-a-container and explained the required flags in a similar way, but adapted for this tool (it likely won't be used so much on system files).
I've tested it and it works fine for me. The same issue may be on Docker rootless, but I guess people will get that and I cannot test it here.

doc: Update docker.rst to explain how to use with podman

---

docs/docker.rst

Based on https://github.com/ocrmypdf/OCRmyPDF/pull/1488:
I prefer to write the name in full aka `jbarlow83/ocrmypdf-alpine` and I'd also suggest to document this because:
* if you use `docker tag` this AFAIK only tags the currently downloaded (=pulled) version of that image
* in case a new update comes out, the new one will not be pulled automatically and one would have to pull and tag the image locally, again
* This `docker tag`  command is easily overlooked, if users just run `docker run ocrmypdf` this may or may not work, depending on how it is resolved.
Also, AFAIK if one could get Docker to register https://hub.docker.com/ocrmypdf then this would suddenly be used instead of your image (currently `podman pull docker.io/ocrmypdf` returns a 404 for me, though)
* It is more common to …

doc: Update docker.rst to use full image tag

---

src/ocrmypdf/hocrtransform/_hocr.py

When processing certain HOCR files, the `_get_text_direction` method can receive a `None` value for its `par` parameter. This occurs when either:
1. The HOCR file lacks properly structured paragraph elements (`<p class='ocr_par'>`)
2. The fallback case is triggered but `self.hocr.find(...)` returns `None`
Without a check for this condition, the method attempts to access `par.attrib` on a `None` object, resulting in an `AttributeError`:
```
AttributeError: 'NoneType' object has no attribute 'attrib'
```
This PR adds a simple null check to handle the case where `par` is `None`, returning the default left-to-right text direction instead of crashing.
This change:
- Prevents crashes when processing HOCR files with missing or malformed paragraph structures
- Maintains backward compatibility …

fix ._hocr
