ocrmypdf/OCRmyPDF

ocrmypdf/hocrtransform.py

Makes it consistent with the other scripts.  Thanks!

fix shebang in hocrtransform.py

---

README.rst

Let's encourage using the simplest installation procedure.

README: Debian and Ubuntu installation option

---

pytest.ini

This was causing problems for me.  Thanks.

also exclude .git in pytest.ini

---

docs/cookbook.rst

Fixed language option example (French)

---

setup.py
src/ocrmypdf/_pipeline.py
src/ocrmypdf/exec/jbig2enc.py
src/ocrmypdf/exec/pngquant.py
src/ocrmypdf/exec/qpdf.py
src/ocrmypdf/optimize.py
src/ocrmypdf/pdfa.py

See https://lgtm.com/projects/g/jbarlow83/OCRmyPDF for details.

Fix some recommendations from LGTM

---

.docker/alpine.dockerfile
.dockerignore

This Dockerfile creates a 762MB sized image based on the alpine python3 image.

Add Dockerfile based on alpine:3.9

---

README.md

Hi and thanks a lot for OCRmyPDF!
I'd like to offer a few spelling corrections. Also, I've made two links HTTPS and added instructions for Arch Linux.

Fix typos, add instructions for training data

---

docs/batch.rst

Fixes https://github.com/jbarlow83/OCRmyPDF/issues/498

Fixes docker-compose.yaml file

---

docs/installation.rst

Add installation instructions for Windows/Cygwin64

---

src/ocrmypdf/subprocess/__init__.py

After upgrading from 11.3.4 to 11.4.4 I'm getting lots of warnings about unclosed file handles when running test cases in my project. All the test cases run the API `ocr()` method.
```
paperless_tesseract/tests/test_parser.py::TestParser::test_simple_digital
/home/jonas/.local/share/virtualenvs/paperless-RxYopU_u/lib/python3.6/site-packages/ocrmypdf/_exec/ghostscript.py:248: ResourceWarning: unclosed file <_io.TextIOWrapper name=18 encoding='utf-8'>
callback=GhostscriptFollower(progressbar_class),
```
This PR fixes this issue.
------------
A couple questions regarding test cases:
I've run the test cases and got 30% overall coverage. Did I do something wrong or is this the current state?
You can also dramatically increase test suite execution time on multi-core system by enabling parallel …

Fix unclosed file warnings.

---

docs/api.rst

[skip ci] Update api.rst

---

docs/jbig2.rst

Two minor additions of missing words

[ci skip] Update jbig2.rst

---

setup.cfg

There are breaking changes, but I could not find any reference to them in the code.

Allow pluggy v1.

---

setup.cfg
src/ocrmypdf/_version.py
src/ocrmypdf/pdfa.py

Signed-off-by: Marco Genasci <fedeliallalinea@gmail.com>

fixs importlib.{metadata,resource} for new python version

---

src/ocrmypdf/optimize.py

This PR solves for me an issue #846

Wrap exception of non-CMYK images into the log warning

---

src/ocrmypdf/pdfinfo/info.py

This PR makes OCRmyPDF log a warning instead failing with an exception when pikepdf encounters an image with an unreadable ICC profile and raises `UnsupportedImageTypeError("ICC profile corrupt or not readable")`.
See https://github.com/pikepdf/pikepdf/issues/346.
Example log output:
```
Unreadable image: ICC profile corrupt or not readable. <ImageInfo '/Im1' image 306x405 Colorspace.icc None 8 Encoding.jpeg 72.000000x72.000018>
```
I’m not exactly sure of the effect on the OCR and resulting document. Will the offending image just be skipped from OCR? Will it be missing from the output PDF?

Log a warning instead of failing on images with a corrupt ICC profile.

---

docs/advanced.rst

Tesseract old wiki is no longer maintained

Fix tesseract documentation url

---

misc/watcher.py

This logs the "done" message if neither delete nor archive options are set.

log completion message

---

misc/watcher.py

added setting RETRIES_LOADING_FILE to avoid giving up to early

added setting RETRIES_LOADING_FILE to watcher.py

---

src/ocrmypdf/pdfinfo/info.py

This fixes an issue I'm having with processing a (presumably poorly structured) PDF. It's very similar to https://github.com/ocrmypdf/OCRmyPDF/issues/1052

handle case when candidate is None

---

src/ocrmypdf/_validation.py
src/ocrmypdf/cli.py

Fix randomly ordered languages from set()

---

misc/completion/ocrmypdf.fish

Change skip-ocr to skip-text for fish completion

---

misc/batch.py

Added a function to archive originals and avoid calling ocrmypdf if they are still is PDF/A. Also there was a typo in the example code.

batch example: added archive, small corrections and optimizations

---

docs/languages.rst

Adding language install docs for archlinux

Adding language install docs for archlinux

---

snapcraft.yaml

Fix wrong env var for GS path in Snap

---

docs/installation.rst

docs: update installation.rst

---

.gitignore
README_ZH.md

Easy to read in Chinese, there may be some translation is wrong, please audit

doc: add readme zh markdown file
